#!/usr/bin/env python3
"""Generate tools/m4/blob/rookie_names.inc from rookies.LAST_TABLE/FIRST_TABLE.

Writes nasm `db` lines (labels last_names: and first_names:) with the
NUL-padded mixed-case name bytes the C4 pools store. Run by build_dynasty.py
before nasm; rookie_fill.asm does `%include "rookie_names.inc"`.
"""
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_TOOLS = os.path.dirname(os.path.dirname(_HERE))
if _TOOLS not in sys.path:
    sys.path.insert(0, _TOOLS)

from m4.rookies import LAST_TABLE, FIRST_TABLE  # noqa: E402

OUT = os.path.join(_HERE, "rookie_names.inc")


def _emit(tbl, label, per_line=16):
    lines = [label + ":"]
    data = b"".join(tbl)
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("        db " + ", ".join(str(b) for b in chunk))
    return "\n".join(lines)


def main():
    text = ("; generated by gen_names.py from m4.rookies LAST_TABLE / "
            "FIRST_TABLE\n; do not edit by hand\n\n"
            + _emit(LAST_TABLE, "last_names") + "\n\n"
            + _emit(FIRST_TABLE, "first_names") + "\n")
    open(OUT, "w").write(text)
    print("%s: %d + %d bytes of name data"
          % (OUT, 12 * len(LAST_TABLE), 8 * len(FIRST_TABLE)))


if __name__ == "__main__":
    main()
